config/routes.rb
MyMovieTracker::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new', as: 'signup'
  end

  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end

  unauthenticated do
    root to: 'homes#show', via: :get
  end

  resources :users, only: [:show] do
    resource :settings, only: [:show] do
      member do
        post 'save_movie_list'
      end
    end
  end

  resources :actors, only: [:show]
  resources :movies, only: [:show, :create, :destroy, :update]
  resources :lists, only: [:show, :index]
  resource :search, only: [:show]

  get 'profile/:id', to: 'users#show', as: 'profile'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'
  get '/422', to: 'errors#unprocessable_entity'
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/views/home/index.html.erb
<title><%= page_title %></title>
<div class="row">
  <div class="col-md-12">
    <div class="main_search">
	    <div class="form-group">
		    <%= form_tag(:search, url: search_path, method: "get") do %>
			    <%= text_field_tag (:query), nil, class: "form-control" %>
			    <%= submit_tag ("Search"), class: "btn btn-default" %>
			    <p><%= radio_button_tag(:type, "movie", checked: true) %>
			    <%= label_tag(:type_movie, "Movie") %>
			    <%= radio_button_tag(:type, "actor") %>
			    <%= label_tag(:type_actor, "Actor") %></p>
		    <% end %>
	    </div>
    </div>
    <div class="main_create_profile">
	    <h3>Create a profile to login and keep track of the movies you've seen! <%= link_to "Sign up now!", signup_path %></h3>
    </div>
  </div>
</div>