config/routes.rb
MyMovieTracker::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new', as: 'signup'
  end

  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end

  unauthenticated do
    root to: 'homes#show', via: :get
  end

  resources :users, only: [:show] do
    resource :settings, only: [:show] do
      member do
        post 'save_movie_list'
      end
    end
  end

  resources :actors, only: [:show]
  resources :movies, only: [:show, :create, :destroy, :update]
  resources :lists, only: [:show, :index]
  resource :search, only: [:show]

  get 'profile/:id', to: 'users#show', as: 'profile'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'
  get '/422', to: 'errors#unprocessable_entity'
end

app/views/shared_javascripts/create.js.erb
$("#<%= params[:movie_id] %>-tr").removeClass("movie-unwatched").addClass("movie-watched");
$("#<%= params[:movie_id] %>-form").attr({'method':"delete", 'action':"<%= escape_javascript(movie_path(params[:movie_id])) %>"});

if ($('#moviecount').length) {
  var count = $("#moviecount").html();
  $('#moviecount').text(parseInt(count)+1);
};

app/views/shared_javascripts/destroy.js.erb
$("#<%= params[:movie_id] %>-tr").removeClass("movie-watched").addClass("movie-unwatched");
$("#<%= params[:movie_id] %>-form").attr({'method':"post", 'action':"<%= escape_javascript(movies_path) %>"});
$("#<%= params[:movie_id] %>-tr").find("[name='-method']").attr('value', "post");

if ($('#moviecount').length) {
  var count = $("#moviecount").html();
  $('#moviecount').text(parseInt(count)-1);
};