config/routes.rb
MyMovieTracker::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new', as: 'signup'
  end

  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end

  unauthenticated do
    root to: 'homes#show', via: :get
  end

  resources :users, only: [:show] do
    resource :settings, only: [:show] do
      member do
        post 'save_movie_list'
      end
    end
  end

  resources :actors, only: [:show]
  resources :movies, only: [:show, :create, :destroy, :update]
  resources :lists, only: [:show, :index]
  resource :search, only: [:show]

  get 'profile/:id', to: 'users#show', as: 'profile'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'
  get '/422', to: 'errors#unprocessable_entity'
end

app/models/search.rb
class Search
  SEARCH_TYPES = %w(movie actor)

  def initialize(current_user_movies, args = {})
    @current_user_movies = current_user_movies
    @query = args[:query]
    @type = args[:type]
  end

  def partial
    SEARCH_TYPES.include?(@type) ? @type : 'movie'
  end

  def view_partial
    @current_user_movies.nil? ? 'list_of_movies_not_signed_in' : 'list_of_movies'
  end

  def list
    response['results']
  end

  def list_renderable
    list.map { |movie| Tmdb::Movie.new(movie) }
  end

  def list_count
    response['total_results']
  end

  def compare_list_to_user
    @current_user_movies.compare_to(list)
  end

  private

  def response
    @_response = @type == 'movie' ? search_by_movie_title(@query) : search_by_actor(@query)
  end

  def search_by_movie_title(title)
    Tmdb::TheMovieDb.search_by_movie_title(title)
  end

  def search_by_actor(actor)
    Tmdb::TheMovieDb.search_by_actor(actor)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_filter :define_paths

  def index
    @querystring = params[:query]
    @type = params[:type]
    if @type == 'actor'
      @render = 'actor'
    else
      @render = 'movie'
      @search_movies_list = Tmdb::TheMovieDb.search_by_movie_title(@querystring)
      if user_signed_in?
        get_movies_if_user_signed_in
        @ourmovies =  Tmdb::MovieStats.compare_movies(@allmovies,@search_movies_list['results'])[0]
        @listpart = '/shared_partials/list_of_movies'
      else
        @listpart = '/shared_partials/list_of_movies_not_signed_in'
      end
    end
  end

  def define_paths
    @jpathc = 'create'
    @jpathd = 'destroy'
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search = Search.new(current_user_movies, query: params[:query], type: params[:type])
  end
end

app/helpers/search_helper.rb
module SearchHelper

	def list_movies(movie)
		Tmdb::TheMovieDb.search_by_movie_title(movie)
  end

  def list_people(actor)
    Tmdb::TheMovieDb.search_by_actor(actor)
	end

end

app/views/searches/_actor.html.erb
Number of results: <%= search.list_count %>

<table>
	<% search.list.each do |actor| %>
		<tr>
			<td><%= image_tag Tmdb::PICTURE_URL + actor['profile_path'] unless actor['profile_path'].nil? %></td>
			<td><%= link_to actor['name'], actor_path(actor['id']) %></td>
		</tr>
	<% end %>
</table>

app/views/searches/_list_of_movies.html.erb
<% form_data = ive_seen_it(movie.id, @search.compare_list_to_user) %>
<tr class="<%= form_data.trclass %>" id = "<%= movie.id %>-tr">
  <td><%= image_tag (movie.poster_path) %></td>
  <td><%= link_to (movie.title + " (#{movie.release_date})"), movie_path(movie.id) %></td>
  <td><%= ive_seen_it_button(form_data, movie) %></td>
  <td><%= admin? movie %>
</tr>

app/views/searches/_list_of_movies_not_signed_in.html.erb
<tr class="noclass" id= "<%= movie.id %>-tr">
  <td><%= image_tag (movie.poster_path) %></td>
  <td><%= link_to (movie.title + " (#{movie.release_date})"), movie_path(movie.id) %></td>
</tr>

app/views/searches/_movie.html.erb
Number of results: <%= search.list_count %>
<table>
  <tr class="movie-status-table-header">
    <th></th>
    <th>Film</th>
  </tr>
  <tr>
    <%= render partial: search.view_partial, collection: search.list_renderable, as: :movie %>
	</tr>
</table>

app/views/searches/show.html.erb
<%= provide :title, 'Search Results' %>
<table>
<% unless params[:query].blank? %>
  <%= render @search.partial, search: @search %>
<% else %>
  <% flash.now[:notice] = "Please enter a valid search word" %>
<% end %>